# This workflow will automatically generate and commit ApexDocs to the `/docs/` directory
# to be served on GitHub Pages

name: apexdocs

on:
  push:
    branches: [ "main" ] 

permissions:
  contents: write

jobs:
  generate-apex-docs:
    permissions:
      contents: write # for the action to checkout, and commit generated documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install apexdocs
        run: npm i -g @cparra/apexdocs
      - name: Re-generate Apexdocs
        run: |
          rm -rf docs
          apexdocs-generate -s packages/core/main/default/classes -t docs -r -p global public
      - name: Commit new documentation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "🤖 Automated Documentation"
          git push
